---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
  - name: mvbcoding/awslinux

suites:
  - name: default
    run_list:
      - recipe[veneur::default]
    attributes:
      veneur:
        user: vagrant
